---
apiVersion:     v1
kind:           Secret

metadata:
    name:       datos-secretos-bbdd

data:
    password:       bWlwYXNzd29yZA== # echo -n 'mipassword' | base64                                                          
    root-password:  bWlwYXNzd29yZA== # echo -n 'mipassword' | base64                                                          
    user:           bWl1c3Vhcmlv #echo -n 'miusuario' | base64                                                           
